### ISSUE TITLE
可以考虑接入element-ui-helper的doc代码,节省开发时间.

### ISSUE THREAD

**Issue by tiansin** [mxp131011/element-plus-doc#1]
下面这个插件作者很久没更新了,但愿能早点用作者的插件替换掉掉它🤣
https://github.com/HULANG-BTB/element-ui-helper/tree/master/src/document

**Comment by mxp131011** [comment]
element-ui-helper 太老了，没有参考意义，现在已经完成大约70个组件了，还有28个左右没完成，预计明天完成，

**Comment by tiansin** [comment]
牛逼,我跪拜了... 大佬有没有兴趣把vxetable也搞进去.

**Comment by mxp131011** [comment]
> 牛逼,我跪拜了...大佬有没有兴趣把vxetable也搞进去.

不想整理文档了，如果你可以把`vxetable`的文档整理出来，我可以加上，[文档示例](https://github.com/mxp131011/element-plus-doc/tree/master/src/documents/modules)，顺便说一下，现在本插件所有组件已经整理完成了，已经正式可用了

**Comment by tiansin** [comment]
> > 牛逼,我跪拜了...大佬有没有兴趣把vxetable也搞进去.
> 
> 不想整理文档了，如果你可以把`vxetable`的文档整理出来，我可以加上，[文档示例](https://github.com/mxp131011/element-plus-doc/tree/master/src/documents/modules)，顺便说一下，现在本插件所有组件已经整理完成了，已经正式可用了

感谢,已经用上了,我有时间整理一下vxetable的文档.另外可否加个语言的配置,我这智能提示显示的是英文,有可能因为系统是英文的原因.

**Comment by mxp131011** [comment]
好的，明天找个时间加上

**Comment by mxp131011** [comment]
> > > 牛逼,我跪拜了...大佬有没有兴趣把vxetable也搞进去.
> > 
> > 
> > 不想整理文档了，如果你可以把的文档整理出来，我可以加上，[文档示例](https://github.com/mxp131011/element-plus-doc/tree/master/src/documents/modules)，顺便说一下，现在本插件所有组件已经整理完成了，已经正式可用了`vxetable`
> 
> 感谢，已经用上了，我有时间整理一下vxetable的文档.另外可否加个语言的配置，我这智能提示显示的是英文，有可能因为系统是英文的原因.

好的，明天加上

**Comment by mxp131011** [comment]
> > > 牛逼,我跪拜了...大佬有没有兴趣把vxetable也搞进去.
> > 
> > 
> > 不想整理文档了，如果你可以把`vxetable`的文档整理出来，我可以加上，[文档示例](https://github.com/mxp131011/element-plus-doc/tree/master/src/documents/modules)，顺便说一下，现在本插件所有组件已经整理完成了，已经正式可用了
> 
> 感谢,已经用上了,我有时间整理一下vxetable的文档.另外可否加个语言的配置,我这智能提示显示的是英文,有可能因为系统是英文的原因.

已支持设置默认语言

**Comment by tiansin** [comment]
> > > > 牛逼,我跪拜了...大佬有没有兴趣把vxetable也搞进去.
> > > 
> > > 
> > > 不想整理文档了，如果你可以把`vxetable`的文档整理出来，我可以加上，[文档示例](https://github.com/mxp131011/element-plus-doc/tree/master/src/documents/modules)，顺便说一下，现在本插件所有组件已经整理完成了，已经正式可用了
> > 
> > 
> > 感谢,已经用上了,我有时间整理一下vxetable的文档.另外可否加个语言的配置,我这智能提示显示的是英文,有可能因为系统是英文的原因.
> 
> 已支持设置默认语言

Perfect!
