### ISSUE TITLE
希望 可以选择不显示下划线提示语.. 

### ISSUE THREAD

**Issue by mydoge** [mxp131011/element-plus-doc#4]
代码里面 一堆 下划线非常影响看代码.. 

希望优化该功能,

**Comment by getxifan** [comment]
![image](https://user-images.githubusercontent.com/128971573/230057136-e97bea82-47a8-45b2-a202-4c658bb5f94c.png)

**Comment by getxifan** [comment]
非常感谢您

**Comment by mydoge** [comment]
哇 真的更新了, 非常感谢作者
