### ISSUE TITLE
启用此扩展时，vscode无法在设置ui中加载所有扩展的所有设置

### ISSUE THREAD

**Issue by Gerrnperl** [mxp131011/element-plus-doc#7]
When this extension is enabled, all settings of all extensions could not be loaded in settings ui.

vscode的设置的扩展设置部分无法加载，经扩展二等分定位到此扩展。

此问题在vscode 1.83.0更新后出现, 在windows10 和 Kubuntu 23.04均成功复现。

![enabled](https://github.com/mxp131011/element-plus-doc/assets/64595686/d3a35a18-0cef-4bb2-a338-f5fb8db3e867)
![disabled](https://github.com/mxp131011/element-plus-doc/assets/64595686/34075cf3-9cd8-488c-8b26-39cacffcd730)

**Comment by mxp131011** [comment]
已修复
